name: ci

on:
  push:
    branches: [debug, main, release]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain: [stable, nightly]
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        components: rustfmt, clippy
        override: true
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose
    - name: build no-default-features
      run: cargo build --no-default-features --verbose
    - name: test no-default-features
      run: cargo test --no-default-features --tests --verbose
